[package]
name = "bevy_dioxus_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.66"
syn = { version = "2", features = ["full"] }
quote = "^1.0.26"
convert_case = "^0.6.0"

[lib]
proc-macro = true
